import Head from 'next/head'
import Link from "next/link";
import { useState, useEffect } from "react";
import styles from '../styles/Home.module.css'
import MainHeader from './mainHeader'

function Layout ({children}: any) {
  return (
    <div className={`${styles.container} container`}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainHeader />
      <main className={`${styles.main}`}>
        {children}
      </main>

      <footer className={styles.footer}>
        <Link href="/"><a>hogehoge</a></Link>
      </footer>
    </div>
  )
}
export default Layout