import Head from 'next/head'
import Link from "next/link";
import styles from '../styles/Home.module.css'
import LoginButton from './login-btn'

function Layout ({children}: any) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <LoginButton />
        {children}
      </main>

      <footer className={styles.footer}>
        <Link href="/"><a>hogehoge</a></Link>
      </footer>
    </div>
  )
}
export default Layout