import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import LoginButton from './login-btn'

const Layout = ({children}: any) => (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <LoginButton />
        {children}
      </main>

      <footer className={styles.footer}>
        hogehoge
      </footer>
    </div>
)
export default Layout